services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://maheshkumarsaini8769_db_user:mahesh99830@ac-cf9ozuy-shard-00-00.bvul13j.mongodb.net:27017,ac-cf9ozuy-shard-00-02.bvul13j.mongodb.net:27017,ac-cf9ozuy-shard-00-01.bvul13j.mongodb.net:27017/sunsky?authSource=admin&retryWrites=true&w=majority&tls=true"
      ADMIN_PASSWORD: "sunsky@2026"
      ADMIN_SECRET: "sunsky-docker-secret"
